### ISSUE TITLE
Tracking: API / Building block implementations

### ISSUE THREAD

**Issue by mikeee** [dapr/rust-sdk#124]
Building blocks:

- 🟠 AI / Conversation
  - [x] Implementation
  - [ ] Tool calling
  - [ ] Docs
  - [x] Validation/Example(s)
- 🟢 Service invocation
  - [x] Implementation
  - [x] Docs #126
  - [x] Validation/Example(s)
- 🟠 State management
  - [x] Implementation [TBA](#)
  - [x] Docs #126
  - [ ] Refactor/Add Methods [TBA](#)
  - [x] Validation/Example(s)
  - [x] Query #115 
- 🟠 PubSub messaging
  - [x] Implementation
  - [x] Docs #126
  - [x] Macro(s) #87 
  - [ ] Bulk Pub/Sub [TBA](#)
  - [x] Validation/Example(s)
- 🟠 Bindings
  - [x] Implementation [TBA](#)
  - [ ] Docs [TBA](#)
  - [ ] Macro(s) [TBA](#)
  - [x] Validation/Example(s)
- 🟠 Actors
  - [x] Implementation #99 
  - [ ] Docs [TBA](#)
  - [x] Macro(s)
  - [ ] Add missing client methods [TBA](#)
  - [x] Validation/Example(s)
- 🟠 Secrets management 🟠
  - [x] Implementation
  - [ ] Docs [TBA](#)
  - [x] Bulk secret retrieval method #122
  - [x] Validation/Example(s)
- 🟠 Configuration 🟠
  - [x] Implementation [TBA](#)
  - [ ] Docs [TBA](#)
  - [x] Validation/Example(s)
- 🔴 Distributed lock
  - [ ] Implementation #86 
  - [ ] Docs [TBA](#)
  - [ ] Validation/Example(s) [TBA](#)
- 🔴 Workflow
  - [ ] Implementation #142
  - [ ] Docs [TBA](#)
  - [ ] Validation/Example(s) [TBA](#)
- 🟠 Cryptography
  - [x] Implementation #133
  - [ ] Docs [TBA](#)
  - [x] Validation/Example(s) #133
- 🟠 Metadata
  - [x] Implementation
  - [ ] Docs [TBA](#)
  - [ ] Validation/Example(s) [TBA](#)
- 🟠Jobs
  - [x] Implementation
  - [ ] Docs
  - [x] Validation/Examples

**Comment by zedgell** [comment]
@mikeee I got time this week to work on the workflow. I recommend breaking it into two PRs, one for the durabletask client in rust and the other for the dapr implementation.

**Comment by mikeee** [comment]
@zedgell - Indeed! Sounds like a plan, would you be able to open issues for these with outlines of what your planned implementation will cover?

**Comment by zedgell** [comment]
> @zedgell - Indeed! Sounds like a plan, would you be able to open issues for these with outlines of what your planned implementation will cover?

@mikeee https://github.com/dapr/rust-sdk/issues/142
